### PR TITLE
e2e blocks workflow deployment

### PR DESCRIPTION
**Pull request by amineau**
https://platform-dev-e2e-blocks-deployment.bimdata.io

## Description
The e2e is fixed, it can now integrate the deployment workflow.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have tested my code.
- [ ] I want to run the tests for the commits of this PR

### CODE REVIEW

**Comment by amineau** [comment]
@Amoki @NicolasRichel 
Would you like a mechanism to skip the e2e tests ?
It could also be useful for the automatic upgrades of the viewer.

ex : `[skip e2e]` in the end of commit

**Comment by NicolasRichel** [comment]
> Would you like a mechanism to skip the e2e tests ?

@amineau  Yes, I think it would be very useful in several scenarios.

**Review by NicolasRichel — APPROVED** [review]

**Review by Amoki — APPROVED** [review]

**Review by NicolasRichel — APPROVED** [review]

**Comment by amineau** [comment]
So, finally, there will be two mechanisms to disable the end-to-end tests :
 - Add `[skip e2e]` in the commit message for all commits on main branches (develop, next, main)
 - Uncheck the new line in the PR template named `I want to run the tests for the commits of this PR`. This will disable all e2e jobs for the PR commits, but not for the merge commit.

**Review by Amoki — APPROVED** [review]

**Pull request merged**
